# Generated by Django 2.0.4 on 2018-04-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='birth_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
