# Generated by Django 2.0.4 on 2018-05-12 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0003_new_field_20180421_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='friends',
            name='user',
        ),
        migrations.AddField(
            model_name='frienduser',
            name='friend_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='friends.Friends'),
        ),
        migrations.AddField(
            model_name='frienduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
