# Generated by Django 2.0.4 on 2018-05-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_friend_user_separate_20180512_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frienduser',
            old_name='friend_id',
            new_name='friend',
        ),
    ]
